#!/usr/bin/bash

source /home/icart/catkin_ws/devel/setup.bash;
gnome-terminal -- bash -c " roslaunch orne_bringup orne_alpha.launch; bash" 
sleep 3
gnome-terminal -- bash -c "roslaunch orne_navigation_executor build_map_teleop.launch; bash"
gnome-terminal -- bash -c " roslaunch orne_bringup vlp16.launch; bash" 
#source /opt/ros/kinetic/setup.bash;
