#!/usr/bin/bash

source /home/icart/catkin_ws/devel/setup.bash;
gnome-terminal -- bash -c "roslaunch orne_bringup orne_alpha.launch; bash" 
sleep 3
gnome-terminal -- bash -c "roslaunch orne_bringup vlp16.launch; bash"
sleep 3
gnome-terminal -- bash -c "roslaunch orne_navigation_executor play_waypoints_nav_alpha.launch map_file:=/home/icart/map/gakkou_chizu0603 waypoints_file:=/home/icart/waypoints_file/waypoint_alpha_gakkou0603.yaml init_pos_file:=/home/icart/init_pose_file/18_kai.yaml; bash"


