#!/usr/bin/bash

source /home/icart/catkin_ws/devel/setup.bash;
gnome-terminal -- bash -c "roslaunch orne_bringup orne_alpha.launch; bash" 
sleep 3
gnome-terminal -- bash -c "roslaunch orne_bringup vlp16.launch; bash"
sleep 3
gnome-terminal -- bash -c "roslaunch orne_navigation_executor play_waypoints_nav_alpha.launch map_file:=/home/icart/Desktop/lawn_map/lawn waypoints_file:=/home/icart/Desktop/lawn_map/way.yaml;bash"


